name: Remove data records

on:
  workflow_dispatch:
    inputs:
      arxiv_ids:
        description: 'Arxiv_ids to remove'
        required: true
        type: string
      option:
        description: 'Choose which file to remove'
        required: true
        type: string
        default: "both"
    
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: 'pip'
        cache-dependency-path: |
            requirements-build.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements-build.txt
        python -m pip install -r requirements-summarizer.txt
    - name: Remove files
      run: |
        python scripts/data ${{ github.event.inputs.arxiv_ids }} ${{ github.event.inputs.option }}
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add data/
        timestamp=$(date -u)
        git commit -m "Remove arxiv's from input/output: ${timestamp}" || exit 0
        git push
